apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.env }}-service
  labels:
    app: {{ .Chart.Name }}-{{ .Values.env }}
    environment_name: {{ .Values.env }}
    app_name: {{.Chart.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-{{ .Values.env }}